# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tChat
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'SnapKit'
	pod 'ProgressHUD'
	pod 'SDWebImage'
	pod 'GeoFire'
	pod 'FBSDKLoginKit'
	pod 'GoogleSignIn'
	pod 'Kingfisher'
end
