# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tChat
    pod 'Firebase/Analytics'
  target 'tChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
